### ISSUE TITLE
Upgrade Required

### ISSUE THREAD

**Issue by dxgi** [arnoson/monaco-lua-example#1] opened 2021-12-21 10:12 UTC
I did what's on the README.MD

**Comment by arnoson** [comment] 2021-12-21 10:18
Can you provide more information?
What doesn't work and what errors do you get? And what do you mean by 'update required`, are the dependencies outdated?

**Comment by dxgi** [comment] 2021-12-21 12:07
After starting the server it just says Update Required

**Comment by arnoson** [comment] 2021-12-21 14:17
Unfortunately I can't reproduce your error. I had some different errors though because of the npm workspace names. Made a small fix for this.
Could you provide a screenshot of the `Update Required` log? Also note: currently the lua language server only works on linux!

**Comment by arnoson** [comment] 2022-02-24 21:04
Closing this issue as I can't do anything without more information on the error.

**Closed as completed by arnoson** 2022-02-24 21:04 UTC
Labels: needs clarification

**Comment by Tamim468** [comment] 2023-01-03 08:25
> Can you provide more information? What doesn't work and what errors do you get? And what do you mean by 'update required`, are the dependencies outdated?

Yeah it's probably outdated, i got this issue too saying upgrade required, all i had to do is just git clone your repo and npm run build in that location then install ts-node and start the server then go to the localhost, and it said "upgrade required", you probably have to use the latest language server or latest monaco-languageclient or what you said
